//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""40a14979-50e8-4c17-80e5-4c4387aff25a"",
            ""actions"": [
                {
                    ""name"": ""Primary Target"",
                    ""type"": ""Button"",
                    ""id"": ""8d297320-166d-43a0-9a77-d6877fdcbc60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Target"",
                    ""type"": ""Button"",
                    ""id"": ""474a526f-23bd-47fc-ad17-9c5ed46abaf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Third Target"",
                    ""type"": ""Button"",
                    ""id"": ""841074b6-b9c5-4b3d-9833-aca6fd1e5b0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fourth Target"",
                    ""type"": ""Button"",
                    ""id"": ""cbf634b6-b13c-469a-bc7d-20cefdc678e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""c80d3dda-77f1-40f3-8856-1dbe283d0393"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""36d884a7-ad77-424f-a890-eec48ba1ffcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fifth Target"",
                    ""type"": ""Button"",
                    ""id"": ""cbcb5375-790e-46be-bdfe-43f776d198a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""87bcf78c-166b-4c1a-8e17-aa62058c86af"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78249cf4-283d-4863-bfe0-65ec07bb5f9e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Secondary Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""929292a4-deb2-4d53-8537-2b6a2b3cd7e5"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Third Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd899d16-6bac-4c7c-a1fe-35b4197f2a8c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73ebc30-7caf-4c76-bbdc-ee4433913cef"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69d97975-5b81-4b58-9d7d-61c6553859e1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fourth Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4022dbd5-2beb-41bd-afab-6d0adf8bf84a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fifth Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_PrimaryTarget = m_Camera.FindAction("Primary Target", throwIfNotFound: true);
        m_Camera_SecondaryTarget = m_Camera.FindAction("Secondary Target", throwIfNotFound: true);
        m_Camera_ThirdTarget = m_Camera.FindAction("Third Target", throwIfNotFound: true);
        m_Camera_FourthTarget = m_Camera.FindAction("Fourth Target", throwIfNotFound: true);
        m_Camera_Stop = m_Camera.FindAction("Stop", throwIfNotFound: true);
        m_Camera_Undo = m_Camera.FindAction("Undo", throwIfNotFound: true);
        m_Camera_FifthTarget = m_Camera.FindAction("Fifth Target", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_PrimaryTarget;
    private readonly InputAction m_Camera_SecondaryTarget;
    private readonly InputAction m_Camera_ThirdTarget;
    private readonly InputAction m_Camera_FourthTarget;
    private readonly InputAction m_Camera_Stop;
    private readonly InputAction m_Camera_Undo;
    private readonly InputAction m_Camera_FifthTarget;
    public struct CameraActions
    {
        private @PlayerActions m_Wrapper;
        public CameraActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTarget => m_Wrapper.m_Camera_PrimaryTarget;
        public InputAction @SecondaryTarget => m_Wrapper.m_Camera_SecondaryTarget;
        public InputAction @ThirdTarget => m_Wrapper.m_Camera_ThirdTarget;
        public InputAction @FourthTarget => m_Wrapper.m_Camera_FourthTarget;
        public InputAction @Stop => m_Wrapper.m_Camera_Stop;
        public InputAction @Undo => m_Wrapper.m_Camera_Undo;
        public InputAction @FifthTarget => m_Wrapper.m_Camera_FifthTarget;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @PrimaryTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @PrimaryTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @PrimaryTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @SecondaryTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @SecondaryTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @SecondaryTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @ThirdTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @ThirdTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @ThirdTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @FourthTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @FourthTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @FourthTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @Stop.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Undo.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @Undo.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @Undo.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @FifthTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
                @FifthTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
                @FifthTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryTarget.started += instance.OnPrimaryTarget;
                @PrimaryTarget.performed += instance.OnPrimaryTarget;
                @PrimaryTarget.canceled += instance.OnPrimaryTarget;
                @SecondaryTarget.started += instance.OnSecondaryTarget;
                @SecondaryTarget.performed += instance.OnSecondaryTarget;
                @SecondaryTarget.canceled += instance.OnSecondaryTarget;
                @ThirdTarget.started += instance.OnThirdTarget;
                @ThirdTarget.performed += instance.OnThirdTarget;
                @ThirdTarget.canceled += instance.OnThirdTarget;
                @FourthTarget.started += instance.OnFourthTarget;
                @FourthTarget.performed += instance.OnFourthTarget;
                @FourthTarget.canceled += instance.OnFourthTarget;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @Undo.started += instance.OnUndo;
                @Undo.performed += instance.OnUndo;
                @Undo.canceled += instance.OnUndo;
                @FifthTarget.started += instance.OnFifthTarget;
                @FifthTarget.performed += instance.OnFifthTarget;
                @FifthTarget.canceled += instance.OnFifthTarget;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    public interface ICameraActions
    {
        void OnPrimaryTarget(InputAction.CallbackContext context);
        void OnSecondaryTarget(InputAction.CallbackContext context);
        void OnThirdTarget(InputAction.CallbackContext context);
        void OnFourthTarget(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnUndo(InputAction.CallbackContext context);
        void OnFifthTarget(InputAction.CallbackContext context);
    }
}
