//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""40a14979-50e8-4c17-80e5-4c4387aff25a"",
            ""actions"": [
                {
                    ""name"": ""Primary Target"",
                    ""type"": ""Button"",
                    ""id"": ""8d297320-166d-43a0-9a77-d6877fdcbc60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Target"",
                    ""type"": ""Button"",
                    ""id"": ""474a526f-23bd-47fc-ad17-9c5ed46abaf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Third Target"",
                    ""type"": ""Button"",
                    ""id"": ""841074b6-b9c5-4b3d-9833-aca6fd1e5b0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fourth Target"",
                    ""type"": ""Button"",
                    ""id"": ""cbf634b6-b13c-469a-bc7d-20cefdc678e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""c80d3dda-77f1-40f3-8856-1dbe283d0393"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""36d884a7-ad77-424f-a890-eec48ba1ffcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fifth Target"",
                    ""type"": ""Button"",
                    ""id"": ""cbcb5375-790e-46be-bdfe-43f776d198a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""87bcf78c-166b-4c1a-8e17-aa62058c86af"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78249cf4-283d-4863-bfe0-65ec07bb5f9e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Secondary Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""929292a4-deb2-4d53-8537-2b6a2b3cd7e5"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Third Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd899d16-6bac-4c7c-a1fe-35b4197f2a8c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73ebc30-7caf-4c76-bbdc-ee4433913cef"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69d97975-5b81-4b58-9d7d-61c6553859e1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fourth Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4022dbd5-2beb-41bd-afab-6d0adf8bf84a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fifth Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Editor1"",
            ""id"": ""e433ae62-ab9b-4654-ac4c-c1e9185f8fda"",
            ""actions"": [
                {
                    ""name"": ""EditorMode"",
                    ""type"": ""Button"",
                    ""id"": ""529c8823-4276-4480-87ac-e335a1cd36d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddItem1"",
                    ""type"": ""Button"",
                    ""id"": ""17faedfb-70d0-400c-8bad-12e585ee3a9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddItem2"",
                    ""type"": ""Button"",
                    ""id"": ""5dc5ab3b-dedd-48d3-b863-588b4ce1c012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DropItem"",
                    ""type"": ""Button"",
                    ""id"": ""7bf866ec-b419-4200-bc78-4bafb244f41a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""e10167f0-258a-409b-bf60-1f26ad730d2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Button"",
                    ""id"": ""fbbbf774-14e7-4639-9351-9e11903e6227"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""49f095ad-a1bd-4af2-bd0b-fa8ea037be0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""41982cd0-9041-491a-a55f-f67b57af9b99"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EditorMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14142721-f5fe-49f1-8fef-f4a87d225ace"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c82e7133-e243-42f6-ba21-a0c4c016ec53"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78295d30-3718-46cc-9fd4-e7d4be94b4b1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24efe77f-edd6-4de8-9d6e-ed86358c9e8f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d38c3b3b-3df1-469a-a9b8-11d98554646b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f57f8ae8-21fa-4a51-82cf-ea6bd84433b5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_PrimaryTarget = m_Camera.FindAction("Primary Target", throwIfNotFound: true);
        m_Camera_SecondaryTarget = m_Camera.FindAction("Secondary Target", throwIfNotFound: true);
        m_Camera_ThirdTarget = m_Camera.FindAction("Third Target", throwIfNotFound: true);
        m_Camera_FourthTarget = m_Camera.FindAction("Fourth Target", throwIfNotFound: true);
        m_Camera_Stop = m_Camera.FindAction("Stop", throwIfNotFound: true);
        m_Camera_Undo = m_Camera.FindAction("Undo", throwIfNotFound: true);
        m_Camera_FifthTarget = m_Camera.FindAction("Fifth Target", throwIfNotFound: true);
        // Editor1
        m_Editor1 = asset.FindActionMap("Editor1", throwIfNotFound: true);
        m_Editor1_EditorMode = m_Editor1.FindAction("EditorMode", throwIfNotFound: true);
        m_Editor1_AddItem1 = m_Editor1.FindAction("AddItem1", throwIfNotFound: true);
        m_Editor1_AddItem2 = m_Editor1.FindAction("AddItem2", throwIfNotFound: true);
        m_Editor1_DropItem = m_Editor1.FindAction("DropItem", throwIfNotFound: true);
        m_Editor1_Undo = m_Editor1.FindAction("Undo", throwIfNotFound: true);
        m_Editor1_Redo = m_Editor1.FindAction("Redo", throwIfNotFound: true);
        m_Editor1_Save = m_Editor1.FindAction("Save", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_PrimaryTarget;
    private readonly InputAction m_Camera_SecondaryTarget;
    private readonly InputAction m_Camera_ThirdTarget;
    private readonly InputAction m_Camera_FourthTarget;
    private readonly InputAction m_Camera_Stop;
    private readonly InputAction m_Camera_Undo;
    private readonly InputAction m_Camera_FifthTarget;
    public struct CameraActions
    {
        private @PlayerActions m_Wrapper;
        public CameraActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTarget => m_Wrapper.m_Camera_PrimaryTarget;
        public InputAction @SecondaryTarget => m_Wrapper.m_Camera_SecondaryTarget;
        public InputAction @ThirdTarget => m_Wrapper.m_Camera_ThirdTarget;
        public InputAction @FourthTarget => m_Wrapper.m_Camera_FourthTarget;
        public InputAction @Stop => m_Wrapper.m_Camera_Stop;
        public InputAction @Undo => m_Wrapper.m_Camera_Undo;
        public InputAction @FifthTarget => m_Wrapper.m_Camera_FifthTarget;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @PrimaryTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @PrimaryTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @PrimaryTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnPrimaryTarget;
                @SecondaryTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @SecondaryTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @SecondaryTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnSecondaryTarget;
                @ThirdTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @ThirdTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @ThirdTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnThirdTarget;
                @FourthTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @FourthTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @FourthTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnFourthTarget;
                @Stop.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnStop;
                @Undo.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @Undo.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @Undo.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnUndo;
                @FifthTarget.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
                @FifthTarget.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
                @FifthTarget.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnFifthTarget;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryTarget.started += instance.OnPrimaryTarget;
                @PrimaryTarget.performed += instance.OnPrimaryTarget;
                @PrimaryTarget.canceled += instance.OnPrimaryTarget;
                @SecondaryTarget.started += instance.OnSecondaryTarget;
                @SecondaryTarget.performed += instance.OnSecondaryTarget;
                @SecondaryTarget.canceled += instance.OnSecondaryTarget;
                @ThirdTarget.started += instance.OnThirdTarget;
                @ThirdTarget.performed += instance.OnThirdTarget;
                @ThirdTarget.canceled += instance.OnThirdTarget;
                @FourthTarget.started += instance.OnFourthTarget;
                @FourthTarget.performed += instance.OnFourthTarget;
                @FourthTarget.canceled += instance.OnFourthTarget;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @Undo.started += instance.OnUndo;
                @Undo.performed += instance.OnUndo;
                @Undo.canceled += instance.OnUndo;
                @FifthTarget.started += instance.OnFifthTarget;
                @FifthTarget.performed += instance.OnFifthTarget;
                @FifthTarget.canceled += instance.OnFifthTarget;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Editor1
    private readonly InputActionMap m_Editor1;
    private IEditor1Actions m_Editor1ActionsCallbackInterface;
    private readonly InputAction m_Editor1_EditorMode;
    private readonly InputAction m_Editor1_AddItem1;
    private readonly InputAction m_Editor1_AddItem2;
    private readonly InputAction m_Editor1_DropItem;
    private readonly InputAction m_Editor1_Undo;
    private readonly InputAction m_Editor1_Redo;
    private readonly InputAction m_Editor1_Save;
    public struct Editor1Actions
    {
        private @PlayerActions m_Wrapper;
        public Editor1Actions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @EditorMode => m_Wrapper.m_Editor1_EditorMode;
        public InputAction @AddItem1 => m_Wrapper.m_Editor1_AddItem1;
        public InputAction @AddItem2 => m_Wrapper.m_Editor1_AddItem2;
        public InputAction @DropItem => m_Wrapper.m_Editor1_DropItem;
        public InputAction @Undo => m_Wrapper.m_Editor1_Undo;
        public InputAction @Redo => m_Wrapper.m_Editor1_Redo;
        public InputAction @Save => m_Wrapper.m_Editor1_Save;
        public InputActionMap Get() { return m_Wrapper.m_Editor1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Editor1Actions set) { return set.Get(); }
        public void SetCallbacks(IEditor1Actions instance)
        {
            if (m_Wrapper.m_Editor1ActionsCallbackInterface != null)
            {
                @EditorMode.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnEditorMode;
                @EditorMode.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnEditorMode;
                @EditorMode.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnEditorMode;
                @AddItem1.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem1;
                @AddItem1.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem1;
                @AddItem1.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem1;
                @AddItem2.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem2;
                @AddItem2.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem2;
                @AddItem2.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnAddItem2;
                @DropItem.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnDropItem;
                @DropItem.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnDropItem;
                @DropItem.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnDropItem;
                @Undo.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnUndo;
                @Undo.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnUndo;
                @Undo.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnUndo;
                @Redo.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnRedo;
                @Redo.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnRedo;
                @Redo.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnRedo;
                @Save.started -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnSave;
                @Save.performed -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnSave;
                @Save.canceled -= m_Wrapper.m_Editor1ActionsCallbackInterface.OnSave;
            }
            m_Wrapper.m_Editor1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EditorMode.started += instance.OnEditorMode;
                @EditorMode.performed += instance.OnEditorMode;
                @EditorMode.canceled += instance.OnEditorMode;
                @AddItem1.started += instance.OnAddItem1;
                @AddItem1.performed += instance.OnAddItem1;
                @AddItem1.canceled += instance.OnAddItem1;
                @AddItem2.started += instance.OnAddItem2;
                @AddItem2.performed += instance.OnAddItem2;
                @AddItem2.canceled += instance.OnAddItem2;
                @DropItem.started += instance.OnDropItem;
                @DropItem.performed += instance.OnDropItem;
                @DropItem.canceled += instance.OnDropItem;
                @Undo.started += instance.OnUndo;
                @Undo.performed += instance.OnUndo;
                @Undo.canceled += instance.OnUndo;
                @Redo.started += instance.OnRedo;
                @Redo.performed += instance.OnRedo;
                @Redo.canceled += instance.OnRedo;
                @Save.started += instance.OnSave;
                @Save.performed += instance.OnSave;
                @Save.canceled += instance.OnSave;
            }
        }
    }
    public Editor1Actions @Editor1 => new Editor1Actions(this);
    public interface ICameraActions
    {
        void OnPrimaryTarget(InputAction.CallbackContext context);
        void OnSecondaryTarget(InputAction.CallbackContext context);
        void OnThirdTarget(InputAction.CallbackContext context);
        void OnFourthTarget(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnUndo(InputAction.CallbackContext context);
        void OnFifthTarget(InputAction.CallbackContext context);
    }
    public interface IEditor1Actions
    {
        void OnEditorMode(InputAction.CallbackContext context);
        void OnAddItem1(InputAction.CallbackContext context);
        void OnAddItem2(InputAction.CallbackContext context);
        void OnDropItem(InputAction.CallbackContext context);
        void OnUndo(InputAction.CallbackContext context);
        void OnRedo(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
    }
}
